### ISSUE TITLE
Error: import umap_

### ISSUE THREAD

**Issue by saman-abbaspoor** [EricKenjiLee/WaveMAP_Paper#1]
Hi,

I'm trying to run the **WaveMAP_Figures_Data.ipynb** on my google colab but when importing UMAP (**from umap import umap_ as umap**), I keep running into the following error. I updated jax on colab but still the error persists. Any idea how I can fix this?

Thank you in advance,
SAM

`[/usr/local/lib/python3.7/dist-packages/jax/_src/lib/__init__.py](https://localhost:8080/#) in <module>
     73 version_str = jaxlib.version.__version__
     74 version = check_jaxlib_version(
---> 75   jax_version=jax.version.__version__,
     76   jaxlib_version=jaxlib.version.__version__,
     77   minimum_jaxlib_version=jax.version._minimum_jaxlib_version)

AttributeError: module 'jax' has no attribute 'version'`

**Comment by EricKenjiLee** [comment]
Hi Saman,

My first issue report! Very exciting. 

I think this is a problem with some of the auto-installed Colab packages and the versions of packages I had pinned. Also a good reason for containerizing with something like Docker instead of pinning versions. I fixed this by changing sklearn and umap's specified versions to the most recent ones (see below) but this may introduce other problems later in the code; I've only checked that they all import properly.

```
!pip install scikit-learn==1.0.2

!pip install umap-learn==0.5.3
```
